# This is the name of the workflow that will be displayed in the "Actions" tab on GitHub.
name: Deploy Flutter Web to GitHub Pages

# This section defines when the workflow should run.
on:
  # It triggers on every push to the 'main' branch.
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This job is named "build-and-deploy".
  build-and-deploy:
    # The type of runner that the job will run on. 'ubuntu-latest' is a standard choice.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up the Flutter environment.
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable" # Use the stable channel of Flutter.

      # Step 3: Gets all the dependencies for your Flutter project.
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Builds the Flutter web application for release.
      # IMPORTANT: Make sure the base-href matches your repository name.
      - name: Build Flutter web
        run: flutter build web --release --base-href /my_porfolio/

      # Step 5: Deploys the built files from 'build/web' to the 'gh-pages' branch.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          # The 'force_orphan' option creates a clean history on the gh-pages branch.
          force_orphan: true
